/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as combatVerifierSol from "./CombatVerifier.sol";
export type { combatVerifierSol };
import type * as dungeonSol from "./Dungeon.sol";
export type { dungeonSol };
export type { Rune } from "./Rune";
export type { Seeker } from "./Seeker";
